# serverless-compose.yml
services:
  amplify-lambda:
    path: ./amplify-lambda

  amplify-assistants:
    path: ./amplify-assistants
    dependsOn:
      - amplify-lambda

  amplify-lambda-admin:
    path: ./amplify-lambda-admin
    dependsOn:
      - amplify-lambda
      - amplify-assistants
  
  amplify-lambda-api:
    path: ./amplify-lambda-api
    dependsOn:
      - amplify-lambda
      - amplify-assistants

  amplify-lambda-artifacts:
    path: ./amplify-lambda-artifacts
    dependsOn:
      - amplify-lambda
      - amplify-assistants

  amplify-lambda-js:
    path: ./amplify-lambda-js
    dependsOn:
      - amplify-assistants
    
  amplify-lambda-ops:
    path: ./amplify-lambda-ops
    dependsOn:
      - amplify-lambda
      - amplify-assistants
      - amplify-lambda-js

  chat-billing:
    path: ./chat-billing
    dependsOn:
      - amplify-lambda
      - amplify-assistants
      - amplify-lambda-js

  data-disclosure:
    path: ./data-disclosure
    dependsOn:
      - amplify-lambda
      - amplify-assistants
  
  amplify-embedding:
    path: ./embedding
    dependsOn:
      - amplify-lambda
      - amplify-assistants
  
  amplify-object-access:
    path: ./object-access
    dependsOn:
      - amplify-lambda
      - amplify-assistants
      - amplify-embedding
  



  




